### ISSUE TITLE
Feedback on the Comment Captcha Plugin

### ISSUE THREAD

**Issue by ghost** [mecha-cms/extend.plugin.comment-captcha#1]
First of all thank you for the new comment Captcha plugin. I've been able to try it out in production. I could comment with Captcha.

This closes the door for most spammers, at least for angry spam bots, which are massively online.

You may also want to develop a contact form for Mecha v2.

Then the Captcha Form Extension would be interesting.

So I'll deal with it when it's time.

**Comment by taufik-nurrohman** [comment]
Already in my TODO list.
